# .github/workflows/docker-reusable.yml
name: Build & Push Microservice to ACR

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      image_tag:
        required: false
        default: 'latest'
        type: string
    secrets:
      ACR_NAME:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker Image
        run: |
          SERVICE=${{ inputs.service_name }}
          TAG=${{ inputs.image_tag }}
          ACR=${{ secrets.ACR_NAME }}.azurecr.io
          CONTEXT=E_commerce_project/$SERVICE
          IMAGE=$ACR/$SERVICE:$TAG

          docker build -t $IMAGE $CONTEXT
          docker push $IMAGE
