name: Build and Push to ACR (Reusable)

on:
  workflow_call:
    inputs:
      acr-name:
        required: true
        type: string
      acr-login-server:
        required: true
        type: string
      docker-image-name:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via Federated Identity
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ inputs.acr-name }}

      - name: Build and Push Docker image
        run: |
          IMAGE=${{ inputs.acr-login-server }}/${{ inputs.docker-image-name }}:latest
          echo "Building image $IMAGE from Dockerfile at ${{ inputs.dockerfile-path }}"
          docker build -t $IMAGE ${{ inputs.dockerfile-path }}
          docker push $IMAGE
